import { readFileSync, writeFileSync } from "node:fs";

const packageJsonPath = "./package.json";
const constantsFilename = "./src/constants.ts";

const readPackageJson = () => {
  const content = readFileSync(packageJsonPath, { encoding: "utf8" });
  return JSON.parse(content);
};

const generateConstantsFile = (packageMetadata) => {
  const { name, description, version, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split("T")[0];

  return `// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.mjs
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "${name}",
  DESCRIPTION: "${description}",
  REPOSITORY: "${repository}",
  AUTHOR: "${author}",
  VERSION: "${version}",
  VERSION_DATE: "${dateOnly}",
  VERSION_DATE_ISO: "${dateIso}",
});

export const LONG_VERSION_DATE = "${version} (${dateOnly})";
`;
};

const main = () => {
  console.info("[generate-version] generating src/constants.ts...");
  const packageMetadata = readPackageJson();
  const data = generateConstantsFile(packageMetadata);
  writeFileSync(constantsFilename, data, { encoding: "utf8" });
  console.info(`[generate-version] ${constantsFilename} written (v${packageMetadata.version})`);
};

main();
